namespace: falco
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./templates/clusterrole.yaml
- ./templates/clusterrolebinding.yaml
- ./templates/configmap.yaml
- ./templates/daemonset.yaml
- ./templates/serviceaccount.yaml
commonLabels:
  app: falco
configMapGenerator:
- name: falco-rules-custom
  files:
  - rules-custom.yaml=configs/rules-custom.cfg
patches:
- ./patch-daemonset.yaml
