apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco
  namespace: default
  labels:
    app.kubernetes.io/instance: falco
    app.kubernetes.io/name: falco
    app.kubernetes.io/version: "0.32.2"
rules:
- resources:
  - nodes
  - namespaces
  - pods
  - replicationcontrollers
  - replicasets
  - services
  - daemonsets
  - deployments
  - events
  - configmaps
  apiGroups:
  - extensions
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  apiGroups:
  - apps
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /healthz
  - /healthz/*
  verbs:
  - get
