apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco
  namespace: default
  labels:
    app.kubernetes.io/instance: falco
    app.kubernetes.io/name: falco
    app.kubernetes.io/version: "0.32.2"
roleRef:
  name: falco
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: falco
  namespace: default
  kind: ServiceAccount
