apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: default
  labels:
    app.kubernetes.io/instance: falco
    app.kubernetes.io/name: falco
    app.kubernetes.io/version: "0.32.2"
